P.register("cvfVersion",function(){return{version:"0.1.0.0-2017-09-01"}});
P.when("A","cvfFormDataGenerator","ready").register("cvf-account-switcher",function(g,l){function n(b,c){b.preventDefault();var e=l.retrieveFormData(b.target),f=e.inputData.serializeArray();f.push(d(b.target));g.ajax(window.location.protocol+"//"+window.location.host+e.requestPath,{method:"POST",params:f,success:c,error:a})}function d(a){a=b(a);var c=a.attr("name");c||(c=a.closest(".cvf-account-switcher-sign-out-link").attr("data-name"));var d=a.attr("value");d||(d=a.closest(".cvf-account-switcher-sign-out-link").attr("data-value"));
return{name:c,value:d}}function a(a,b,c){g.trigger(e.error,c)}function f(a){a=/([^@\s]+)@([a-zA-Z0-9_-]+)(\.[a-zA-Z0-9._-]+)/ig.exec(a);var b;b=a[1];var c=b.length;if(1!==c){for(var d=b.charAt(0),e=0;e<c-2;e++)d+="*";b=d+=b.charAt(c-1)}b+="@";d=a[2];c=d.length;d=d.charAt(0);for(e=0;e<c-1;e++)d+="*";return b+d+a[3]}function c(){0===b(".cvf-account-switcher-check-mark:visible").length&&b(".cvf-account-switcher-check-mark-area").remove()}var b=g.$,e={success:"cvf:account_switcher:success",error:"cvf:account_switcher:error"};
(function(){var a=b("#ap-account-switcher-container")[0],d=window.MutationObserver||window.WebKitMutationObserver;if(void 0!==a&&void 0!==d){var e=new d(function(a){a.forEach(function(a){null!==a.addedNodes&&(c(),e.disconnect())})});e.observe(a,{attributes:!0,childList:!0,characterData:!0,subtree:!0})}})();(function(){b(".cvf-account-switcher-sign-out-link").live("click",function(a){n(a,function(d){if(d.succeeded){var h="."+b(a.target).attr("class").match(/cvf-account-switcher-account-group-\w+/g)[0];
b(h+"-hide").hide();b(h+"-name").text(b("#cvf-account-switcher-sign-out-replace-text").text());b(h+"-claim").text(f(b(h+"-claim").text()));b(h+"-image").replaceWith(b("<div />").append(b("#cvf-account-switcher-sign-out-replace-image").clone().removeClass("cvf-hidden")).html());b(h+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher");d=d.switchedAccountId;void 0!==d&&(d=".cvf-account-switcher-account-group-"+d,b(d+"-check-mark").show(),b(d+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher"));
c()}else g.trigger(e.error,d)})})})()});
P.when("A","cvfVersion","cvfFormDataGenerator","ready").register("cvf",function(g,l,n){function d(a){function d(a){u.options.spinnerTarget&&u.options.spinnerTarget.hide();a.hasOwnProperty("error")?g.trigger(x.error,a.error):a.redirectUrl?window.location=a.redirectUrl:a.redirect?(g.trigger(x.success,a.token,a.status,a.redirect),u.options.autoDestroy?u.destroy():(f(".cvf-widget-alert").hide(),a.status?f(".cvf-widget-status-success").show():f(".cvf-widget-status-error").show(),k()),g.trigger("cvf:verification:complete",
a.status),A.find(".cvf-widget-btn").unbind("click",h),A.find(".cvf-widget-btn-val").unbind("click",h),g.off(x.success),g.off(x.error)):(A.html(a.replace(/<form/g,"<div").replace(/<\/form/g,"</div")),t())}function h(a,b){a.preventDefault();f(".cvf-widget-alert").hide();u.options.spinnerTarget&&u.options.spinnerTarget.show();var c=n.retrieveFormData(a.target),e=c.inputData.serializeArray();b&&e.push(n.getNameValue(a.target));g.ajax(v+c.requestPath,{method:"POST",params:e,success:d,error:y})}function l(a){13===
a.keyCode&&h(a)}function t(){A.find(".cvf-widget-btn").click(function(a){h(a,!1)});A.find(".cvf-widget-btn-val").click(function(a){h(a,!0)});A.find('input[name="code"]').focus().keypress(l)}function q(a){return function(b,c,d){"timeout"!==c||3<=E?g.trigger(x.error,d):g.delay(a,10*E++)}}function y(a,b,c){u.options.spinnerTarget&&u.options.spinnerTarget.hide();g.trigger(x.error,c)}function k(){f.each(A.find("input"),function(a,b){var c=f(b);c.attr("disabled","disabled");c.hasClass("a-input-text")?c.addClass("a-form-disabled"):
c.hasClass("a-button-input")?c.closest(".a-button").addClass("a-button-disabled"):c.closest(".a-input-text-wrapper").length&&c.closest(".a-input-text-wrapper").addClass("a-form-disabled")});f.each(A.find("a"),function(a,b){var c=f(b);c.hasClass("cvf-widget-link-disable-target")&&c.addClass("cvf-link-disabled")})}var u=this;b++;var x={success:"cvf:"+b+":success",error:"cvf:"+b+":error"};u.options={};f.extend(u.options,c,a);(function(a){if(1!==f(a.target).length)throw Error("The CVF widget requires a unique element.");
if(!f.isFunction(a.onSuccess))throw Error("The CVF widget requires a success callback function.");if(!f.isFunction(a.onError))throw Error("The CVF widget requires an error callback function.");})(u.options);var v=u.options.server,A=f(u.options.target);g.on(x.success,u.options.onSuccess);g.on(x.error,u.options.onError);u.start=function(){if(0===f.trim(u.options.requestToken).length)throw Error("The CVF widget requires a request token.");g.ajax(v+"/ap/cvf/request.embed?requestToken="+u.options.requestToken,
{method:"GET",params:e,success:d,error:q(u.start)})};u.destroy=function(){A.html("")};t();var E=0;u.options.autoStart&&u.start()}function a(a){return new d(a)}var f=g.$,c={server:"",target:void 0,requestToken:void 0,onSuccess:void 0,onError:void 0,spinnerTarget:void 0,autoStart:!0,autoDestroy:!0},b=0,e=[{name:"CVFVersion",value:l.version},{name:"AUIVersion",value:P.AUI_BUILD_DATE}];g.on("cvf:verification:request",function(b){var c=f("#"+b),d=c.data("token"),e=c.data("spinnerId"),e=f("#"+e);a({target:c,
spinnerTarget:e,requestToken:d,onSuccess:function(a,c,d){g.trigger("cvf:verification:complete:"+b,a,c,d)},onError:function(a){g.trigger("cvf:verification:error:"+b,a)},autoStart:!0,autoDestroy:!1})});return{create:a}});
P.when("A","cvf","ready").execute(function(g,l){var n=g.$;n(document).ready(function(){function d(a,b,c){window.location=c;console.log("Client Side: "+a)}function a(a){console.log(a)}var f=n(".cvf-widget-spinner"),c=n("#cvf-widget-content");if(1===c.length){var b=n('[name="requestToken"]').first().attr("value");l.create({target:c,spinnerTarget:f,requestToken:b,onSuccess:d,onError:a,autoStart:!1})}})});
P.when("A").execute(function(g){g.declarative("auth-popup","click",function(g){var n=g.data;g=g.$target.closest("a")[0];(n=window.open(g.href,g.target,n.windowOptions))&&n.focus()})});P.when("A","cvfFormDataGenerator","ready").execute(function(g,l){});
P.when("A","cvfFormDataGenerator","ready").execute(function(g,l){var n=g.$;n(".cvf-widget-btn-val").click(function(d){var a=n(d.target).closest(".cvf-widget-form");d=l.getNameValue(n(d.target));a.append('<input type="hidden" name="'+d.name+'" value="'+d.value+'">').submit()})});
P.when("A","ready").register("cvfFormDataGenerator",function(g){var l=g.$;return{retrieveFormData:function(g){g=l(g).closest(".cvf-widget-form");return{requestPath:g.data("use-only-form-action")?g.attr("action"):"/ap/cvf/"+g.attr("action")+".embed",inputData:g.find(".cvf-widget-input,.cvf-widget-hidden-fields,.cvf-widget-input :input"),form:g}},getNameValue:function(g){g=l(g);var d=g.attr("name");d||(d=g.closest(".cvf-widget-btn-val").attr("data-name"));var a=g.attr("value");a||(a=g.closest(".cvf-widget-btn-val").attr("data-value"));
return{name:d,value:a}}}});P.when("A","ready").register("codeResendTimer",function(g){function l(l,d,a){var f=(new Date).getTime(),c=setInterval(function(){var b=(new Date).getTime()-f,b=l-b;if(0>=b)clearInterval(c),g.$("#timer").html(a);else{var b=Math.floor(b/1E3),e=d.split(" +timeleft+ "),b=e[0].split('"').join("")+b+e[1].split('"').join("");g.$("#timer").html(b)}},100)}return{createTimer:function(g,d,a){return new l(g,d,a)}}});